### PR TITLE
update all dependancies, upgrade to prisma 4.16.1 and change engine type

### LINKED ISSUE #134: Superliminal
Oopsy doopsy somebody killed my chat :'(
Let's hunt this bug and exterminate the segfault!

### PR DESCRIPTION
**Pull request by tsiguenz**
Fix from [here](https://github.com/prisma/prisma/issues/10649)
Hope it's working for my arm homies 🙏

### CODE REVIEW

**Comment by tsiguenz** [comment]
The fix is not working, we have other errors now

**Comment by tsiguenz** [comment]
@Crysicia you can try to fix on my commit or try to downgrade to a more stable version.

**Comment by Crysicia** [comment]
Well it's not working my boy :/

**Review by Crysicia — CHANGES_REQUESTED** [review]
Vilebrequin C'est pété gif

**Comment by bhardin** [comment]
Thanks for trying

**Comment by Crysicia** [comment]
@tsiguenz Shall we close this PR now ?
As it will probably never be resolved 😱

**Pull request closed without merging**
